---
apiVersion: v1
kind: Namespace
metadata:
 name: kubernetes-cluster-jitendralabhi
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: spring-boot-app
 namespace: kubernetes-cluster-jitendralabhi
 labels:
  app: spring-boot-app
spec:
 replicas: 4
 selector:
  matchLabels:
   app: spring-boot-app
 template:
  metadata:
   labels:
    app: spring-boot-app
  spec:
   containers:
    - name: spring-boot-app-pod
      image: jitulabhi/i-jitendralabhi-master
      ports:
      - containerPort: 8090
      envFrom:
      - configMapRef:
         name: app-settings
      - secretRef:
         name: secret-info
---
apiVersion: v1
kind: Service
metadata:
 name: spring-boot-app-svc
 namespace: kubernetes-cluster-jitendralabhi
 labels:
  kind: service
spec:
 type: LoadBalancer
 selector: 
   app: spring-boot-app
 ports:
   - protocol: TCP
     port: 8080
     targetPort: 8090


